"""empty message

Revision ID: c601fd848420
Revises: 4c5090438dd9
Create Date: 2022-01-09 22:35:51.101502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c601fd848420'
down_revision = '4c5090438dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lat', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('lng', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lng')
    op.drop_column('users', 'lat')
    # ### end Alembic commands ###
