"""empty message

Revision ID: f01b04ada56f
Revises: f6394b9138f5
Create Date: 2022-01-09 17:03:22.276176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01b04ada56f'
down_revision = 'f6394b9138f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['activation_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
