"""empty message

Revision ID: f6394b9138f5
Revises: ac22a9d0c062
Create Date: 2022-01-09 17:01:17.613422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6394b9138f5'
down_revision = 'ac22a9d0c062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'users', ['activation_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
